export interface IDeletesSqls {
  DELETE_VERSION_MIGRATE: string;
  DELETE_TECHS_BY_REPOSITORY_ID: string;
  DELETE_LIKES_BY_REPOSITORY_ID: string;
  DELETE_REPOSITORY_BY_ID: string;
  TRUNCATE_TABLE: string;
}
